In [56]:
import pandas as pd
munchange = []
for year in range(1999,2020):
    if year < 2018:
        municipalchanges = pd.read_csv("GI_{}.csv".format(year), sep = ";")  # For every csv file
    else: 
        municipalchanges = pd.read_csv("GI_{}.csv".format(year), sep = ",")  # For every csv file
    ## Drop row provence change (provence change is not necessary for dataframe)
    if year == 2002:
        municipalchanges = municipalchanges.drop([13])
    #Change codes in csv file to match electionresult files
    for i,j in enumerate(municipalchanges["Gemeente Code Old"]):
        if j <= 10:
            municipalchanges.loc[i,"Gemeente Code Old"] = 'G000{}'.format(j)
        elif j <= 100:
            municipalchanges.loc[i,"Gemeente Code Old"] = 'G00{}'.format(j)
        elif j <= 1000:
            municipalchanges.loc[i,"Gemeente Code Old"] = 'G0{}'.format(j)
        else: 
            municipalchanges.loc[i,"Gemeente Code Old"] = 'G{}'.format(j)
    for i,j in enumerate(municipalchanges["Gemeente Code New"]):
        if j <= 100:
            municipalchanges.loc[i,"Gemeente Code New"] = 'G00{}'.format(j)
        elif j <= 1000:
            municipalchanges.loc[i,"Gemeente Code New"] = 'G0{}'.format(j)
        else: 
            municipalchanges.loc[i,"Gemeente Code New"] = 'G{}'.format(j)
    munchange.append(municipalchanges)

In [57]:
Kerncijfers = []
for year in range(1998,2018):
    df = pd.read_csv("Variables/Kerncijfers/Kerncijfers_{}".format(year), sep = ";")
    df = df.drop(["Perioden"],axis = 1)
    columnlist = ["Regio's","Totpop{}","Totauto{}","Totallo{}","Homeprice{}","Uitk{}","Regiocode"]
    
    for index, columnname in enumerate(columnlist[1:-1]):
        columnlist[index+1] = columnname.format(year)
    columndict = {}
    for index, oldname in enumerate(df.columns):
        columndict[oldname] = columnlist[index]
    df = df.rename(columndict,axis = "columns")
    columnlist.remove("Regiocode")
    columnlist.insert(0,"Regiocode")
    df= df[columnlist]
    if year <2007:
        df= df.drop('Uitk{}'.format(year),axis =1)
    Kerncijfers.append(df)

for i,k in enumerate(Kerncijfers):
    if i ==0: 
        dfkerncijfers = Kerncijfers[0] 
    else:
        dfkerncijfers = dfkerncijfers.merge(Kerncijfers[i].set_index("Regio's","Regiocode"), on=["Regio's","Regiocode"], how = "outer")
        
for i,j in enumerate(dfkerncijfers["Regiocode"]):
    if isinstance(dfkerncijfers.iloc[i,0], str):
        dfkerncijfers.iloc[i,0] = j.replace("M","").rstrip()

nameskern = dfkerncijfers[["Regiocode","Regio's"]]

dfkerncijfers = dfkerncijfers.drop("Regio's",axis = 1).dropna(how = "all")

dfkerncijfers = dfkerncijfers.merge(nameskern, on = ["Regiocode"] )

display(dfkerncijfers)

,Regiocode,Totpop1998,Totauto1998,Totallo1998,Homeprice1998,Totpop1999,Totauto1999,Totallo1999,Homeprice1999,Totpop2000,...,Totauto2016,Totallo2016,Homeprice2016,Uitk2016,Totpop2017,Totauto2017,Totallo2017,Homeprice2017,Uitk2017,Regio's
0,G1680,24806.0,23427.0,1379.0,79.0,24751.0,23393.0,1358.0,80.0,24824.0,...,23755.0,1488.0,2339.0,2130.0,25286.0,23702.0,1584.0,2406.0,2080.0,Aa en Hunze
1,G0738,11529.0,11181.0,348.0,105.0,11691.0,11324.0,367.0,105.0,11774.0,...,12325.0,713.0,1173.0,700.0,13067.0,12308.0,759.0,1206.0,650.0,Aalburg
2,G0358,22600.0,20242.0,2358.0,103.0,22513.0,20115.0,2398.0,103.0,22461.0,...,25640.0,5659.0,3586.0,1730.0,31373.0,25517.0,5856.0,3698.0,1640.0,Aalsmeer
3,G0197,18782.0,16916.0,1866.0,67.0,18713.0,16870.0,1843.0,68.0,18699.0,...,23952.0,2960.0,2147.0,1960.0,27047.0,23894.0,3153.0,2197.0,1830.0,Aalten
4,G0480,9163.0,8617.0,546.0,94.0,9130.0,8568.0,562.0,95.0,9074.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ter Aar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,G1930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,66086.0,19207.0,6398.0,8210.0,85401.0,65742.0,19659.0,6536.0,8010.0,Nissewaard
603,G1945,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29870.0,4704.0,3320.0,3460.0,34764.0,29871.0,4893.0,3363.0,3300.0,Berg en Dal
604,G1940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,47594.0,3671.0,4557.0,3790.0,51585.0,47583.0,4002.0,4690.0,3530.0,De Fryske Marren
605,G1942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45331.0,11365.0,8563.0,3660.0,56935.0,45346.0,11589.0,8866.0,3600.0,Gooise Meren
606,G1948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,79869.0,69178.0,10691.0,8240.0,5680.0,Meierijstad

In [58]:
dfhomepr2007 = pd.read_csv("Variables/Kerncijfers/Woningenvanaf2007", sep = ";")
dfhomepr2007 = dfhomepr2007.drop(["ID","KoppelvariabeleRegioCode_306"],axis = 1)
for i,j in enumerate(dfhomepr2007["Perioden"]):
    dfhomepr2007.iloc[i,1] = j.replace("JJ00","")
dfhomepr2007= dfhomepr2007.rename({"GemiddeldeWoningwaarde_99": "Homeprice","RegioS":"Regiocode"},axis = 1)

for i,j in enumerate(dfhomepr2007["Regiocode"]):
    if isinstance(dfhomepr2007.iloc[i,0], str):
        dfhomepr2007.iloc[i,0] = j.replace("M","").rstrip()


dfhomepr2007 = dfhomepr2007.pivot(index ='Regiocode', columns ='Perioden')
dfhomepr2007.columns = [''.join(col) for col in dfhomepr2007.columns.values]


dfhomepr2007 = dfhomepr2007.dropna(axis = 0, how = "all")

dfhomepr2007.iloc[:,0:] = dfhomepr2007.iloc[:,0:].astype(float)
dfhomepr2007.iloc[:,0:] = dfhomepr2007.iloc[:,0:].astype(float)


for i in dfhomepr2007:
    for index, j in enumerate(dfkerncijfers["Regiocode"]):
        if j in dfhomepr2007.index.values.tolist():
            dfkerncijfers.loc[index, i] = dfhomepr2007.loc[j,i]

In [59]:
for i,j in enumerate(dfkerncijfers["Regiocode"]):
    if j == "G0893":
        dfkerncijfers.iloc[i,-1] == "Bergen (L.)"

In [60]:

for Municipalchanges in munchange:
    #     display(Municipalchanges)
    #     Computing old values to new
        regiocodeoldlist = Municipalchanges['Gemeente Code Old'].tolist()
        for i,j in enumerate(dfkerncijfers["Regiocode"]):
            if j in regiocodeoldlist:
                for index, oldcode in enumerate(Municipalchanges["Gemeente Code Old"]):
                    if oldcode == j:
                        dfkerncijfers.iloc[i,0] = Municipalchanges.iloc[index, 2]
                        dfkerncijfers.iloc[i,-1] = Municipalchanges.iloc[index, 3]
                        
for index,naam in enumerate(dfkerncijfers["Regio's"]):
    dfkerncijfers.iloc[index,-1] = naam.rstrip()
    
for year in range(1998,2018):
    dfkerncijfers["Totpop{}".format(year)] = dfkerncijfers.groupby(["Regio's","Regiocode"])['Totpop{}'.format(year)].transform('sum')
    dfkerncijfers["Totauto{}".format(year)] = dfkerncijfers.groupby(["Regio's","Regiocode"])['Totauto{}'.format(year)].transform('sum')
    dfkerncijfers["Totallo{}".format(year)] = dfkerncijfers.groupby(["Regio's","Regiocode"])['Totallo{}'.format(year)].transform('sum')
    dfkerncijfers["Homeprice{}".format(year)] = dfkerncijfers.groupby(["Regio's","Regiocode"])['Homeprice{}'.format(year)].transform('sum')
    if year > 2006:
        dfkerncijfers["Uitk{}".format(year)] = dfkerncijfers.groupby(["Regio's","Regiocode"])['Uitk{}'.format(year)].transform('sum')    

dfkerncijfers = dfkerncijfers.drop_duplicates(subset=["Regio's"])

In [61]:
uitktot2006 = pd.read_csv("Variables/uitktot2006.csv", index_col = 0)
uitktot2006 = uitktot2006.rename(columns={'RegiocodeKoppelvariabele_1': 'Regiocode'})
dfkerncijfers = dfkerncijfers.merge(uitktot2006, on = ["Regiocode"], how = "outer" )

In [62]:
for year in range(1999,2018):
    dfkerncijfers["Uitk{}".format(year)]  = ((dfkerncijfers["Uitk{}".format(year)]/dfkerncijfers["Totpop{}".format(year)])*100)

In [92]:
for year in range(1998,2017):
    dfkerncijfers["avgpopchange{}".format(year+1)] = ((dfkerncijfers["Totpop{}".format(year+1)] - dfkerncijfers["Totpop{}".format(year)] )/dfkerncijfers["Totpop{}".format(year)])*100
    dfkerncijfers["avgallochange{}".format(year+1)] = ((dfkerncijfers["Totallo{}".format(year+1)] - dfkerncijfers["Totallo{}".format(year)] )/dfkerncijfers["Totallo{}".format(year)])*100
    dfkerncijfers["avghomepchange{}".format(year+1)] = ((dfkerncijfers["Homeprice{}".format(year+1)] - dfkerncijfers["Homeprice{}".format(year)] )/dfkerncijfers["Homeprice{}".format(year)])*100
    if year == 1998:
        continue
    dfkerncijfers["avguitkchange{}".format(year+1)] = ((dfkerncijfers["Uitk{}".format(year+1)] - dfkerncijfers["Uitk{}".format(year)] )/dfkerncijfers["Uitk{}".format(year)])*100

In [94]:
electionperiods = [[1999,2002,"9802"],[2002,2003,"0203"],[2003,2006,"0306"],[2006,2010,"0610"],[2010,2012,'1012'],[2012,2017,"1217"]]
dfKerncijfers = pd.DataFrame()


for i in electionperiods:
    startyear = i[0]+1

    avg = dfkerncijfers[["Regiocode","avgpopchange{}".format(startyear)]]

    for j in range(i[0]+2,i[1]+1):
        avg = avg.merge(dfkerncijfers[["avgpopchange{}".format(j),"Regiocode"]],how = "right", on = "Regiocode")
#     print(avg)
#     print(avg.iloc[:,1:].mean(axis = 1))
#     break
    dfKerncijfers["avgpopchangeelection{}".format(i[2])] = avg.iloc[:,1:].mean(axis = 1)

    avg = dfkerncijfers[["Regiocode","avgallochange{}".format(startyear)]]
    for j in range(i[0]+2,i[1]+1):
        avg = avg.merge(dfkerncijfers[["avgallochange{}".format(j),"Regiocode"]],how = "right", on = "Regiocode")
    dfKerncijfers["avgallochangeelection{}".format(i[2])] = avg.iloc[:,1:].mean(axis = 1)
    
    avg = dfkerncijfers[["Regiocode","avguitkchange{}".format(startyear)]]
    for j in range(i[0]+2,i[1]+1):
        avg = avg.merge(dfkerncijfers[["avguitkchange{}".format(j),"Regiocode"]],how = "right", on = "Regiocode")
    dfKerncijfers["avguitkchangeelection{}".format(i[2])] = avg.iloc[:,1:].mean(axis = 1)

    avg = dfkerncijfers[["Regiocode","avghomepchange{}".format(startyear)]]
    for j in range(i[0]+2,i[1]+1):
        avg = avg.merge(dfkerncijfers[["avghomepchange{}".format(j),"Regiocode"]],how = "right", on = "Regiocode")
    dfKerncijfers["avghomepchangeelection{}".format(i[2])] = avg.iloc[:,1:].mean(axis = 1)

dfKerncijfers["Regiocode"] = dfkerncijfers["Regiocode"]

In [24]:
dfKerncijfers.to_csv('/Users/ruben/Documents/Datascience & Society/Thesis/Variables/Definitiveversions/Kerncijfers_VERSION.csv')